In [1]:
import pandas as pd
import numpy as np
import joblib
import matplotlib.pyplot as plt

In [3]:
df=pd.read_csv('Students.csv')
df

    Hours  Marks
0       0     34
1       1     36
2       1     33
3       1     39
4       1     42
5       2     45
6       2     38
7       3     45
8       3     53
9       3     46
10      3     56
11      4     59
12      4     55
13      4     56
14      5     72
15      5     59
16      6     62
17      6     71
18      7     78
19      7     88
20      7     61
21      7     74
22      8     71
23      8     89
24      9     82
25      9     67
26      9     89
27     10     81
28     10     82
29     11     79

In [4]:
x=df['Hours'].values.reshape(-1,1)
y=df['Marks'].values.reshape(-1,1)

In [9]:
y

array([[34],
       [36],
       [33],
       [39],
       [42],
       [45],
       [38],
       [45],
       [53],
       [46],
       [56],
       [59],
       [55],
       [56],
       [72],
       [59],
       [62],
       [71],
       [78],
       [88],
       [61],
       [74],
       [71],
       [89],
       [82],
       [67],
       [89],
       [81],
       [82],
       [79]])

In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=42)

ValueError: test_size=30 should be either positive and smaller than the number of samples 30 or a float in the (0, 1) range